CRITICAL - 2022-05-23 17:00:57 --> syntax error, unexpected token "use"
#0 X:\xampp\htdocs\TP3\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('UserController/...')
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('UserController/...')
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 17:01:02 --> syntax error, unexpected token "use"
#0 X:\xampp\htdocs\TP3\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('UserController/...')
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('UserController/...')
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 17:01:06 --> syntax error, unexpected token "use"
#0 X:\xampp\htdocs\TP3\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('UserController/...')
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('UserController/...')
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 17:01:27 --> Call to undefined method App\Controllers\UserController::respond()
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->checkEmail()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-23 17:01:29 --> Call to undefined method App\Controllers\UserController::respond()
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->checkEmail()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-23 17:36:50 --> Call to undefined function App\Controllers\noEmptyVarCreateUser()
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-23 17:37:10 --> Call to undefined function App\Controllers\noEmptyVarCreateUser()
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-23 17:37:15 --> Call to undefined function App\Controllers\noEmptyVarCreateUser()
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-23 17:37:30 --> Call to undefined function App\Controllers\noEmptyVarCreateUser()
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-23 17:39:03 --> Call to undefined function App\Controllers\noEmptyVarCreateUser()
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-23 17:39:05 --> Call to undefined function App\Controllers\noEmptyVarCreateUser()
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2022-05-23 17:46:54 --> Cannot add or update a child row: a foreign key constraint fails (`appweb`.`profiles`, CONSTRAINT `profiles_ibfk_4` FOREIGN KEY (`videos_fk_id`) REFERENCES `videos` (`id`))
CRITICAL - 2022-05-23 17:46:54 --> Cannot add or update a child row: a foreign key constraint fails (`appweb`.`profiles`, CONSTRAINT `profiles_ibfk_4` FOREIGN KEY (`videos_fk_id`) REFERENCES `videos` (`id`))
#0 X:\xampp\htdocs\TP3\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `pr...', 0)
#1 X:\xampp\htdocs\TP3\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 X:\xampp\htdocs\TP3\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 X:\xampp\htdocs\TP3\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 X:\xampp\htdocs\TP3\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 X:\xampp\htdocs\TP3\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 X:\xampp\htdocs\TP3\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 X:\xampp\htdocs\TP3\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(86): CodeIgniter\BaseModel->save(Array)
#9 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#10 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#11 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-05-23 18:15:47 --> syntax error, unexpected token ";", expecting "]"
#0 X:\xampp\htdocs\TP3\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('X:\\xampp\\htdocs...')
#1 X:\xampp\htdocs\TP3\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(797): class_exists('\\App\\Controller...', true)
#4 X:\xampp\htdocs\TP3\system\CodeIgniter.php(406): CodeIgniter\CodeIgniter->startController()
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-23 18:16:16 --> El encriptador necesita una clave de inicio.
#0 X:\xampp\htdocs\TP3\system\Encryption\Encryption.php(124): CodeIgniter\Encryption\Exceptions\EncryptionException::forNeedsStarterKey()
#1 X:\xampp\htdocs\TP3\system\Config\Services.php(215): CodeIgniter\Encryption\Encryption->initialize(Object(Config\Encryption))
#2 X:\xampp\htdocs\TP3\system\Config\BaseService.php(248): CodeIgniter\Config\Services::encrypter()
#3 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(35): CodeIgniter\Config\BaseService::__callStatic('encrypter', Array)
#4 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-05-23 18:17:26 --> CodeIgniter\Config\Services::encrypter(): Argument #1 ($config) must be of type ?Config\Encryption, string given, called in X:\xampp\htdocs\TP3\system\Config\BaseService.php on line 248
#0 X:\xampp\htdocs\TP3\system\Config\BaseService.php(248): CodeIgniter\Config\Services::encrypter('pepino')
#1 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(35): CodeIgniter\Config\BaseService::__callStatic('encrypter', Array)
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#4 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-23 18:37:47 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(20): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 18:38:02 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(20): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 18:38:18 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(20): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 18:39:57 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(19): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 18:40:03 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(19): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 18:42:56 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(24): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 18:43:05 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(24): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 18:46:28 --> Constant expression contains invalid operations
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-23 18:46:45 --> Constant expression contains invalid operations
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-23 18:57:39 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(20): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 18:58:00 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(20): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 19:03:52 --> syntax error, unexpected token ";"
#0 X:\xampp\htdocs\TP3\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('X:\\xampp\\htdocs...')
#1 X:\xampp\htdocs\TP3\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Validations...')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(522): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Validations...')
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(115): CodeIgniter\Validation\Validation->loadRuleSets()
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 19:04:21 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(20): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 19:11:40 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(20): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 19:24:11 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(20): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 19:24:39 --> syntax error, unexpected variable "$data", expecting ")"
#0 X:\xampp\htdocs\TP3\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('X:\\xampp\\htdocs...')
#1 X:\xampp\htdocs\TP3\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Validations...')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(522): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Validations...')
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(115): CodeIgniter\Validation\Validation->loadRuleSets()
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 19:31:46 --> Undefined variable $data
#0 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 15)
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 19:33:25 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(15): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-23 19:36:05 --> Undefined variable $encrypter
#0 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 16)
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 19:36:59 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(16): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-23 19:38:15 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(16): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#4 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-23 19:44:04 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(22): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 19:44:13 --> Descifrado: autenticación fallida.
#0 X:\xampp\htdocs\TP3\system\Encryption\Handlers\OpenSSLHandler.php(98): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 X:\xampp\htdocs\TP3\app\Validations\UserRules.php(22): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(292): App\Validations\UserRules->validateUser('angeles', 'email,password', Array, NULL)
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'angeles', Array, Array)
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 19:48:17 --> syntax error, unexpected token "}", expecting ";"
#0 X:\xampp\htdocs\TP3\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('X:\\xampp\\htdocs...')
#1 X:\xampp\htdocs\TP3\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Validations...')
#2 X:\xampp\htdocs\TP3\system\Validation\Validation.php(522): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Validations...')
#3 X:\xampp\htdocs\TP3\system\Validation\Validation.php(115): CodeIgniter\Validation\Validation->loadRuleSets()
#4 X:\xampp\htdocs\TP3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#5 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-05-23 19:54:03 --> password_hash(): Argument #2 ($algo) must be a valid password hashing algorithm
#0 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(42): password_hash('angeles', '$2y$07$BCryptRe...')
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 20:24:27 --> Undefined array key "email"
#0 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'X:\\xampp\\htdocs...', 29)
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 20:24:52 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\login.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 18)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(58): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 20:25:36 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\login.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 18)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(58): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 20:25:47 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\login.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 18)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(58): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 20:26:23 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\login.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 18)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(58): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 20:27:21 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\login.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 18)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(58): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 20:33:36 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\login.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 18)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(58): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 21:05:56 --> Class "App\Controllers\Exception" not found
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-23 21:13:30 --> Undefined variable $session
#0 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 52)
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->registration()
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 21:17:44 --> Undefined variable $error
#0 X:\xampp\htdocs\TP3\app\Views\login.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 31)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\Home.php(11): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\Home->index()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 21:20:16 --> Undefined variable $session
#0 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(50): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 50)
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 21:21:12 --> Undefined variable $validation
#0 X:\xampp\htdocs\TP3\app\Views\login.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 26)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(53): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 21:41:15 --> Undefined variable $data
#0 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 58)
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 21:43:08 --> Undefined variable $data
#0 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 58)
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#3 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-23 21:44:06 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\login.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 17)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(58): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 21:46:59 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\login.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 17)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(56): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 21:47:00 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\login.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 17)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\UserController.php(56): view('login', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 21:47:15 --> Undefined variable $header
#0 X:\xampp\htdocs\TP3\app\Views\register.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 27)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('register', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(38): view('register', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->index()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 21:54:28 --> Call to undefined function App\Controllers\debug_to_console()
#0 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\UserController->login()
#1 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#2 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2022-05-23 22:09:50 --> Error connecting to the database: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
CRITICAL - 2022-05-23 22:09:50 --> Undefined variable $countries
#0 X:\xampp\htdocs\TP3\app\Views\register.php(67): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 67)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('register', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(44): view('register', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->index()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-05-23 22:09:54 --> Error connecting to the database: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
CRITICAL - 2022-05-23 22:09:54 --> Undefined variable $countries
#0 X:\xampp\htdocs\TP3\app\Views\register.php(67): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 67)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('register', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(44): view('register', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->index()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-05-23 22:10:05 --> Error connecting to the database: MySQL server has gone away
CRITICAL - 2022-05-23 22:10:05 --> Undefined variable $countries
#0 X:\xampp\htdocs\TP3\app\Views\register.php(67): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 67)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('register', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(44): view('register', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->index()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-05-23 22:10:12 --> Error connecting to the database: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
CRITICAL - 2022-05-23 22:10:12 --> Undefined variable $countries
#0 X:\xampp\htdocs\TP3\app\Views\register.php(67): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 67)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('register', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(44): view('register', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->index()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-05-23 22:10:24 --> Error connecting to the database: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
CRITICAL - 2022-05-23 22:10:24 --> Undefined variable $countries
#0 X:\xampp\htdocs\TP3\app\Views\register.php(67): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'X:\\xampp\\htdocs...', 67)
#1 X:\xampp\htdocs\TP3\system\View\View.php(210): include('X:\\xampp\\htdocs...')
#2 X:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 X:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('register', Array, true)
#4 X:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(44): view('register', Array)
#5 X:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->index()
#6 X:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#7 X:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 X:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-23 23:03:59 --> Undefined variable $header
#0 L:\xampp\htdocs\TP3\app\Views\register.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'L:\\xampp\\htdocs...', 27)
#1 L:\xampp\htdocs\TP3\system\View\View.php(210): include('L:\\xampp\\htdocs...')
#2 L:\xampp\htdocs\TP3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 L:\xampp\htdocs\TP3\system\Common.php(1089): CodeIgniter\View\View->render('register', Array, true)
#4 L:\xampp\htdocs\TP3\app\Controllers\RegisterController.php(33): view('register', Array)
#5 L:\xampp\htdocs\TP3\system\CodeIgniter.php(832): App\Controllers\RegisterController->index()
#6 L:\xampp\htdocs\TP3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#7 L:\xampp\htdocs\TP3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 L:\xampp\htdocs\TP3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
